#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
authentication_token:
  path: /authentication_token
  methods: ['POST']
api_me:
  path: '/api/me/{id}'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\MyUserController'
    _api_resource_class: 'App\Entity\Carte'
    _api_collection_operation_name: 'collName_api_me'
user_me:
  path: '/api/user/{id}'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\MyUsermailController'
    _api_resource_class: 'App\Entity\User'
    _api_collection_operation_name: 'collName_api_user'
api_me2:
  path: '/api/items/search/code/{id}'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\DetailController'
    _api_resource_class: 'App\Entity\OrderItem'
    _api_collection_operation_name: 'collName_api_me2'
api_me3:
  path: '/api/detailitems/search/code/{id}'
  methods: ['GET']
  defaults:
    _controller: '\App\Controller\CarteDetailController'
    _api_resource_class: 'App\Entity\CarteDetail'
    _api_collection_operation_name: 'collName_api_me3'
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
upload:
  path: /upload
  controller: App\Controller\Uploadpdf::upload
  methods: POST
